apiVersion: v1
kind: Service
metadata:
  name: {{ include "aggrete.fullname" . }}
  labels: {{- include "aggrete.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "aggrete.selector" . | nindent 4 }}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
